name: Node.js Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This step checks out your repository's code.

      - name: Run Node.js script
        run: node index.js  # Here, you reference the script by its filename.
