name: Manual Script Run

on:
  workflow_dispatch: # This event allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      ORG_NAME: ${{ secrets.ORG_NAME}} #
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        
      - name: Generate a GitHub token
        id: generate-token
        uses: actions/github-script@v5
        with:
          script: |
            const token = await github.actions.createToken({
              scopes: ['repo', 'packages:write'],
            });
            console.log(token);

      - name: Set GH_TOKEN environment variable
        run: |
          echo "GH_TOKEN=${{ steps.generate-token.outputs.token }}" >> $GITHUB_ENV


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # Specify Node.js version 18

      - name: Install dependencies
        run: npm install # If your project has dependencies

      - name: Run Node.js script
        run: node index.js # Replace with the path to your Node.js script
